### ISSUE TITLE
Creating more than 16 spaces

### ISSUE THREAD

**Issue by lopugit** [dado3212/spaces-renamer#43]
I swear back in the day on lion you could make more than 16 spaces.

There's a hack to do this via connecting an external display, making the extra spaces, and then disconnecting it, which moves those spaces to your home displays spaces list creating 32.. So it's obviously semi-supported.

Re: https://superuser.com/questions/893258/how-to-remove-the-limit-of-how-many-desktop-spaces-can-be-opened-in-mission-cont

I was wondering if you might have an inkling on how to do it?

**Comment by dominiklohmann** [comment]
Basically this requires injecting code into Dock.app, which is the sole owner of the connection to the window server, in order to call some internal functions for adding spaces.

You can install [yabai][yabai] and its scripting addition (requires disabling SIP, but you already have that disabled for spaces-renamer anyways), which allows you to run `yabai -m space --create` to create spaces from the command line. 

yabai is a tiling window manager—a tool that manages windows for you automatically by arranging them in binary space partitioned tiles, much like the popular i3 or bspwm for linux. You don't need to use these features if you don't want them, as you can tell yabai to not handle your windows (which is the default behaviour with an empty config file). That way you can just use the functionality for creating spaces.

You can check the wiki of yabai for installation instructions.

[yabai]: https://github.com/koekeishiya/yabai

**Comment by dado3212** [comment]
Marking as closed due to above comment.
