### ISSUE TITLE
Would it be easy to add an option to always expand the screen preview?

### ISSUE THREAD

**Issue by danijar** [dado3212/spaces-renamer#52]
I'm not an expert with Mac software, so this might not make much sense. My understanding is that Spaces Renames reimplements parts of the mission control view in order to display the custom space names. If this is the case, would it be easy to add an option to always expand the screen previews? Usually, one needs to hover the screen names with the mouse for them to expand to previews. However, this is less than ideal for a keyboard-centric workflow and there is no good existing solution to this problem as far as I know.

**Comment by dado3212** [comment]
The actual Mission Control stuff is written in Swift, and I've had a pretty hard time in the past properly hooking into it.  The way SpacesRenamer currently works is pretty janky, and it's by hooking in the actual UI rendering stuff which is ObjC.  This works for changing text boxes, but not for actually properly interacting with SpacesRenamer.  Unfortunately don't have a good way therefore to get it to properly expand.  Marking as `wontfix` because It's not currently easy, but best of luck finding something that works for you.

**Comment by danijar** [comment]
Thanks for the explanation, that makes sense.
