### ISSUE TITLE
 Labels not getting updated

### ISSUE THREAD

**Issue by patrinoua** [dado3212/spaces-renamer#79]
**Describe the bug**
I followed the instructions, also restart the computer afterwards but Desktop labels still don't get updated.

**Versions**
1. MySIMBL version - not applicable
2. Spaces Renamer version - 1.9.1
3. Mac Info: MacOS Big Sur (11.6) 

Thanks in advance! 😊
 
<img width="1792" alt="Screenshot 2021-11-03 at 12 17 11" src="https://user-images.githubusercontent.com/36475005/140052243-5b1c7dc0-7849-45e9-8915-38d5f27c0da9.png">
<img width="1792" alt="Screenshot 2021-11-03 at 12 17 25" src="https://user-images.githubusercontent.com/36475005/140052250-c7ac0736-ef82-4515-8602-8b71e59c8c9d.png">

**Comment by ChristianEllehammer** [comment]
Same issue here, on Macbook Air M1. 
It seems that 'Update Names' is greyed out.

<img width="465" alt="Screenshot 2021-11-20 at 16 16 39" src="https://user-images.githubusercontent.com/11415372/142731695-75e7b8b7-2133-4607-8576-59477991aa45.png">

<img width="590" alt="Screenshot 2021-11-20 at 16 16 50" src="https://user-images.githubusercontent.com/11415372/142731691-8ad35bd1-b7c9-4e3b-8f09-f84371fcd322.png">

**Comment by dumblob** [comment]
It's a bit silly to post this under nearly all open issues in this tracker but here we go.

I had a similar problem and the following sentence I quote (from https://github.com/dado3212/spaces-renamer/issues/74#issuecomment-818411128 ) explained what was the reason (it seems the MacForge as well as spaces-renamer were incorrectly installed for an unknown reason - because in `macOS -> Preferences -> Users & Groups > Login Items` I had only **yellow triangles** for both entries (MacForge as well as spaces-renamer) which means the file the entries were pointing to didn't exist or weren't readable for some reason (permissions?). So I've removed both entries with the ` - ` button (otherwise they could interfere under certain conditions with the repeated manual reinstallation as discussed below).

>If you do not see spaces-renamer in your MacForge plugins then updating names in the spaces-renamer application in your top drawer will not work.

So I followed the recommendation to **not** install spaces-renamer through the "recommendations" in MacForge (I use the latest version) window but **manually** downloaded space-renamer and meticulously followed the steps in the readme in this repo - i.e. first drag & drop `*.bundle` on a running MacForge window, then `killall -9 Dock`, then first double click the `SpacesRenamer.app` file. Then the records in `macOS -> Preferences -> Users & Groups > Login Items` were without yellow triangles and fully working.

And then do **not** be afraid by the button `Update Names` being **greyed out** but just press it anyway!

Feel free to close this issue if it works now for you!

**Comment by gpappala** [comment]
With Monterey, SpaceRenamer does work, provided you have not selected "Reduce transparency" in System Preferences > Accessibility. SpaceRenamer is based on overlaying its own rendering of OSX's Spaces menu bar on top of the original one. However, with "Reduce transparency" on, either overlaying fails or it is overlaid upon again with the original (gray) menu bar.

**Comment by dado3212** [comment]
Closing this, feel free to file a new issue if you're still having problems.
