### ISSUE TITLE
 Doesn't work after updating to Sonoma 14.4

### ISSUE THREAD

**Issue by gitget-good** [dado3212/spaces-renamer#95]
At first it was working.

I think it was Sonoma 14.1 that was running.

I thought it would be fine if it worked with this version, but when I upgraded to 14.4 it stopped working.
14.1 ---> 14.4

----------
The version is as per the top page of this GItHub
spaces-renamer.bundle (1.10.4), and MacForge (a very unofficial 1.2.0 Beta 2).
https://github.com/dado3212/spaces-renamer#:~:text=may%20not%20appear!-,Installation,-(M1/M2/Apple

----------
command#csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled
	Boot-arg Restrictions: disabled
	Kernel Integrity Protections: disabled
	Authenticated Root Requirement: enabled

--------------------

I tried deleting everything and starting again from the beginning, but it doesn't work.

Also, in recovery mode
csrutil enable --without debug --without fs --without nvram --without kext

I remember that when I executed the above command, a message was displayed indicating that it might not work in the near future.

I don't remember if this wording was displayed before Sonoma 14.4.

I don't know what the cause is, but I think something about SIP has probably changed.

I don't know if there is a way to avoid it.

If you know, please let me know.

Or a request to make corrections if necessary.

**Comment by leblaze** [comment]
Not working for me either. I am in sonoma 14.4 as well

**Comment by richjames0** [comment]
Same and I've also been through all the steps again, including disabling library validation which had somehow gone red: https://www.macenhance.com/docs/general/sip-library-validation.html

**Comment by jvthomas90** [comment]
Hey, I'm the guy who first test-drove and reported back on #93 and I can confirm that everything was working well since then, right up until the recent 14.4 update

Actually, quite a few MacForge plugins broke after that 14.4 update.

<img width="398" alt="Screen Shot 2024-03-19 at 05 11 40" src="https://github.com/dado3212/spaces-renamer/assets/69699907/822905c8-799a-4e9d-8b66-e0935e32ff47">

I only use 3, of these:

1. In the case of one (cDock) I had to update to the latest 5.3.3 version fixed it for me since it was patch specifically made to address the recent OS update/breakage.
2. In the case of AfloatX I didn't need to touch the existing plugin at all, what fixed it for me was actually [ditching the custom beta version of MacForge that came bundled with these instructions]( https://github.com/dado3212/spaces-renamer?tab=readme-ov-file#installation-m1m2apple-silicon:~:text=MacForge%20(a%20very%20unofficial%201.2.0%20Beta%202 ) and instead switch to [the latest version]( https://github.com/jslegendre/appcast/blob/master/Beta/MacForge/MacForge.1.2.2-2.zip ) instead.

In the case of spaces-renamer, I'm not sure whether an update needs to be made specifically to address issues that've cropped up in macOS 14.4 or if it's simply a matter of supporting the official release of the MacForge plugin manager but it's probably one of these two issues – and considering the fact that 

- no further tweaks or updates were required to get Spaces Renamer up and running on Sonoma 
- and similar to AfloatX, Spaces Renamer is a simple and straightforward plugin that focuses on providing one single function (as opposed to the swiss-army-knife that is something like cDock)

I'm inclined to believe that the latter is the case, i.e. just like AloatX didn't need to be touched and simply updating MacForge to the latest version's injection mechanism was sufficient to get it up and running, I'm willing to bet that forgoing any further maintainence and reliance on a custom-built in-house version of an outdated MacForge app and injection mechanism will resolve the issue. I mean, that caveat may have been necessary in the early days of Apple Silicone Macs hitting the market but it's been years now and MacEnhance's own version of MacForge has obviously since been subsequently updated enough times to run just fine on M-series chips and Ventura, not to mention the latest i.e. Sonoma.

Anywho, that's my best guess at the moment. Setting speculation aside, the simple facts are that one of my simpler "one trick pony" MacFoge plugins just needed the updated MacForge assistant running with it's new code injection method in order to work with out any additional tweaks or updates to the plugin bundle itself. On the other hand, the cDock app itself needed to get a version update in addition to relying on the newer MacForge assistant to work again. The UI of the Spaces Renamer app obviously hasn't changed much nor does it's simple function of textbox input require any additional updates, and [as you told me prior]( https://github.com/dado3212/spaces-renamer/issues/93#:~:text=there%20hasn%27t%20really%20been%20a%20necessary%20update%20in%20a%20while%2C%20the%20only%20thing%20was%20the%20architecture%20change%20for%20the%20Apple%20Silicon%20devices.%20My%20suspicion%20is%20that%20it%20should%20already%20work ) _"there hasn't really been a necessary update in a while, the only thing was the architecture change for the Apple Silicon devices. My suspicion is that it should already work."_ I'm willing to bet money that once Spaces Renamer supports the newer MacForge version's code injection vector the plugin will work like a charm without any further tinkering required. My $00.02 cents anyway, for whatever it's worth ¯\\\_(ツ)_/¯

**Comment by dado3212** [comment]
Validated that this broke. My suspicion is that @jvthomas90 is correct, and it's just the MacForge update. Will try to get a chance later this week to update + confirm that it's working (now very much motivated to, given that my primary dev environment is now on 14.4).

**Comment by jvthomas90** [comment]
Just unzipping 1.2.2-2 and replacing MacForge in the /Applications folder didn't work for me

Or rather, it would temporarily work (so far so good, expected behavior just like any other app) but I soon realized the version number wouldn't persist...

Eventually ,usually by the second time I launched the app again, MacForge would fall back to v1.1.0 (to be clear, this wasn't a "reversion" to the custom built "1.2.0 beta 2" that currently comes packaged with Spaces Renamer for Apple Silicone builds).

It took me forever to finally figure this out, but once I did it was pretty easy to replicate and confirm. 

1. Before dragging the newest MacForge.app to /Applications do a sanity check and Get Info or check the attributes in Finder's Preview Pane. The version should be 1.2.2-2. 
2. Drag it to /Applications and double-check that the newly overwritten and updated copy is still indeed v1.2.2-2. Cool beans.
3. Open the app and access the "About" page, just to triple check, just cuz. It'll read and 1.2.2-2. Sweet!
4. Quit the app. Twiddle your thumbs and hum the jeapordy tune so that umpteen seconds have passed. Then try to see if steps 1, 2 or 3 still return 1.2.2-2

I'm willing to bet money that the new install never persists and somehow goes down to 1.1.0. At least, that was the bizarrely maddening wall that I kept running into >_<

Assuming this is the same roadblock you've run into, here are the steps I took that eventually fixed the issue, hope this works for you too 

> random sidenote, I actually ended up deleting my entire user account on that Mac and made a new one to log into... Still didn't do a damn thing lol. 
But hey, at least this extreme step of a fresh setup pretty much confirmed that there wasn't any other wierd interference from other apps/extensions/plugins/processes/etc in my environment that was causing this MacForge "version fallback" behavior. 
It was only much later after I'd hit the nuclear option on my account that I eventually stumbled on this (admitedly MUCH simpler) solution:

- [ ] Quit MacForgeHelper via the menubar icon's dropdown menu
- [ ] Uninstall MacForge.app 
    - I had actually used Hazel and CleanMyMac to completely purge everything from my system including the preferences, supporting files and login items too – but this may be overkill tbh. 
    - Try a regular delete app + empty trash maneuver first and see if the rest of these steps still work for you. If not, get one of the many myriad "cleaner" apps to take care of the leftover files for you too.
    - I suspect these files aren't the cause for the interference though, but that's just my intuition.
- [ ] Restart your Mac
- [ ] Unzip MacForge 1.2.2-2
- [ ] **MANUALLY drag** it into `/Applications` before opening it 
    - i.e. don't let the app automatically prompt you to "move itself" to the new location. It never worked for me, I'd just end up with a duplicate v 1.2.2-2 copy in my downloads folder and, of course, the 1.1.0 version of MacForge in /Applications
- [ ] On the other prompt that pops up on first open regarding updates:
    - [ ] **UN-TICK** the oh so tiny checkbox (I forgot what it says, I think "auto install latest version" or something like that.) It's _super small_ and easy to overlook. Don't! Unplug MacForge from updates ASAP (cuz for some strange reason, MacForge considers 1.1.0 "newer than" 1.2.0b2 and 1.2.2-2 ... I guess, because neither of them came from the official channel of Sparkle framework updates?)
    - [ ] **DON'T** click the "check for updates" button either. 
- [ ] Just for safe measure, open the MacForge settings page and make sure the updates checkbox at the bottom of that first "General" tab is also unticked. Responding to the pop up prompt should untick this, but if you want to do a sanity check, this is where you'd locate that setting.

Only at this point after you've adequately dodged and countered all the myriad "automatic adjustments" pop up prompts that turn out to not really be helpful in preserving the MacForge version number should you feel comfortable interacting with that last remaining pop-up window regarding MacForge's "Helper" menubar icon application. 

- [ ] Use Touch ID or type in your password and hit enter to let it install. 

Quit MacForge.app, twiddle your thumbs and hum the tune to Jeaopordy for 30 secs, then launch it again to see if the UI layout for managing plugins, plugin prefs, or the System tab has changed/reverted back to v1.1.0. If it still looks the same as it did 30 seconds ago, you're all set, congrats! 🥳  Best part, you didn't even have to resort to nuking your Mac home folder just to narrow down the list of possible culprits before figuring out the fix... unlike me 😅

**Comment by dado3212** [comment]
No, it's definitely 1.2.2-2, the About is still correct. Will reach out to Jemery on Discord.

**Comment by falquaddoomi** [comment]
Just adding this to the list: I updated my M1 Macbook Pro to Sonoma 14.4.1 today and I can't seem to get Spaces Renamer working, despite following the directions above.

I'm fairly sure that I'm using the MacForge 1.2.2 (2) build -- the "About" page says "1.2.0 Beta 1" above the changelog, but says "Version 1.2.2 (2)" beneath "MacForge". I have all the auto-update checkboxes unchecked and I didn't experience any issues with it reverting to a prior version through multiple launches of the program and restarts of my machine.

Regarding SpacesRenamer, I'm using the copy from the "M1/M2/Apple Silicon" install section from the README, i.e. https://github.com/dado3212/spaces-renamer/files/9235969/spaces-renamer.zip. It appears as version 1.10.4 in the "Manage Plugins" window in MacForge. I copied the bundle from that zip into MacForge's "Plugins" folder and SpacesRenamer.app into `/Applications`, just FYI.

**Comment by Lui22** [comment]
Same here
MacForge says "Version 1.2.2 (2)". Downloaded [here](https://raw.githubusercontent.com/jslegendre/appcast/master/Beta/MacForge/MacForge.1.2.2-2.zip).
All dots green. spaces-renamer 1.10.4. Killed dock. Sonoma 14.4. M1 MBP.

**Comment by falquaddoomi** [comment]
Just FYI, I installed the latest MacForge beta, 1.2.2-3 (https://github.com/jslegendre/appcast/raw/master/Beta/MacForge/MacForge.1.2.2-3.zip) and after a restart and killing the Dock, SpacesRenamer 1.10.4 is working again!

For reference, I'm still on Sonoma 14.4.1 on a 2021 14-inch M1 Macbook Pro.

**Comment by ernestorendon** [comment]
@falquaddoomi 
These exact steps just worked for me!

I'm on Sonoma 14.4.1 on a 2023 14-inch M2 Max MBP :)
SO happy to have this working (somewhat) again!

**Comment by richjames0** [comment]
Same! on Mac Studio Apple Silicon 14.4.1. Hoorah!

**Comment by jvthomas90** [comment]
> Just FYI, I installed the latest MacForge beta, 1.2.2-3 (https://github.com/jslegendre/appcast/raw/master/Beta/MacForge/MacForge.1.2.2-3.zip) and after a restart and killing the Dock, SpacesRenamer 1.10.4 is working again!
> 
> For reference, I'm still on Sonoma 14.4.1 on a 2021 14-inch M1 Macbook Pro.

Ooh, I missed this update, thanks for the headsup and the step-by-step @falquaddoomi much appreciated! 🙏🏽 Can confirm that SpacesRenamer is working once again on my 15-inch M2 Air running Sonoma 14.4.1

Also, I read your earlier post on this thread, I'm glad I was able to steer you towards AfloatX as well :) hope it serves you well! It's been a headache-reliever / lifesaver for me in certain (admittedly niche, but nonetheless oh so frequent) use-cases and situations.

Cheers! （ ^\_^）o🍻o（^_^ ）

**Comment by dado3212** [comment]
@falquaddoomi nice, that worked for me as well! Added it to the README, going to mark this as closed.

**Comment by nynewco** [comment]
One tiny tip ... the Spaces Renamer icon may appear all the way to the left of the menu bar icons and if your resolution is low, you may not see it. So, change display to high resolution so you see all the icons and then you can do Ctrl drag and drop to the rightmost side so it is visible and accessible!
